dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codecov pytest-cov
script:
- pytest --cov=./
after_success:
- codecov
env:
  global:
    secure: A6Wg6WsyGbpHvUqL9hYkxec720wIBNKM0u7kJsU62URi82G5zWsOcHtpQHckC5vGwTfXwOz39cdR/fncddDN0mPLlWhZ367AsYmF84phDHFbhTrwrcxOTIRAS+u4H9hXGifd2XS45ubwUrOZ+mZUJ71qbPoTF+ecEPO0md0ifXGzhMPYoRC/yNJ98IQayGjJozS372mxWpI3VIk6XS9JeKL2X/4jx8S/4mLlkY9u64Ap/MvNOlOktv81+HeaAVHZwK1HYZ8MqJpoh1b+yhCIVX2jMec2VJOM6YRHaWLUk/M3pOZi1wThCXzRt7C76Cx0GwHgjETgjFXjGgN5/q0ugKMFoq9kNZ13/GwVHAXfwfUwl6h0n5wk/29QrPkLjNyHqAqBmwOvz6Q0xFGgiijL9QsgCKWHqKqX6s16jw642qf7+J5ZyjGgyLReSbMiNjvkWmBeXGnN+A+js/ZtV7DgTuYTn1ykZWvgfdsGMCo0JJMhUXzPvEUbsS9I/mojJDcE0i8tlN0tuS2FIxX667FyKNksOcO+4kLjIPhqt6tAu+drJ6JluQ7D4E6KccauflOnVRFF1gskrkMVHUm+k6kI0e87GYmdXJkuqBhBOkT4Gteu/F+/+D2ZrSy4x7zW9Y5TYXmsTSwrEHvdBOWUsFt9vUtqw5jWmBYpKTQNI/lT2r8=
