version: "3"
services:

  src:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: tail -f /dev/null
    environment:
      - DEBUG=True
    ports:
      - 8888:8888
    volumes:
      - ./src:/RoboSchool/src
      - ./data:/RoboSchool/data
      - ./notebooks:/RoboSchool/notebooks
      - ./models:/RoboSchool/models
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - DEBUG=True
    ports:
      - 9999:9999
    volumes:
      - ./app:/RoboSchool/app
    networks:
      - backend

networks:
  backend:
    driver: "bridge"