version: "3"
services:

  src:
    image: fabiansd/rl-env-p37
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      - DEBUG=True
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - .:/RoboSchool
    networks:
      - backend
    container_name: rl-env

  frontend:
      image: fabiansd/node-bomberman
      environment:
        - DEBUG=True
      ports:
        - 3000:3000
      networks:
        - backend
      container_name: bomberman

networks:
  backend:
    driver: "bridge"

