version: "3"
services:

  src:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: tail -f /dev/null
    environment:
      - DEBUG=True
    ports:
      - 8888:8888
    volumes:
      - .:/RoboSchool
    networks:
      - backend

networks:
  backend:
    driver: "bridge"