version: "3"
services:

  src:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    environment:
      - DEBUG=True
    entrypoint:
      - "/bin/bash"
    ports:
      - 8888:8888
    volumes:
      - ./src:/RoboSchool/src
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - DEBUG=True
    ports:
      - 9999:9999
    volumes:
      - ./app:/RoboSchool/app
